apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache1
  namespace: desa1
spec:
  selector:
    matchLabels:
      app: ejemplo-apache
  replicas: 3
  template:
    metadata:
      labels:
        app: ejemplo-apache
    spec:
      containers:
        - name: apache
          image: httpd
          ports:
            - containerPort: 80
